spring:
  # Enable Java 21 Virtual Threads for extreme concurrency
  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/notificationapplication?useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # Automatically creates and updates your tables
    show-sql: true # Prints SQL queries to the console for debugging
    database-platform: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 50MB